### ISSUE TITLE
Java 9 issue

### ISSUE THREAD

**Issue by arkadiuszczapiewskinordea** [NordeaOSS/devtool#3]
When you try to run DevTool with Java 9, there is an exception:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/tools/devtool/1.35/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NullPointerException: Cannot invoke method withInputStream() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.nordea.devtool.Devtool.loadProperties(Devtool.groovy:43)
        at com.nordea.devtool.Devtool.main(Devtool.groovy:31)

**Comment by holmbech** [comment]
Yes. know about it. Luckily its only a warning. Will look at it. But with a lower priority.

**Comment by arkadiuszczapiewskinordea** [comment]
Thanks :) 
The problem is that if you install JDK 9 with DevTool - after that DevTool stops to work (and you cannot even uninstall JDK 9) - you have to manually switch JAVA_HOME to older version to make it work again.

**Comment by slachiewicz** [comment]
Some info about jdk9 and groovy gradle/gradle#2995

**Comment by arkadiuszczapiewskinordea** [comment]
Hi guys!
can we please prioritize that? More uses are installing Java 9 with DevTool (as Java 8 will not be supported by Oracle) and it crashes DevTool...

As we discussed, this can be solved by bundling JRE with DevTool. The only change to be done in that case seems to be a bin/devtool and bin/devtool.bat files so they won't use default but bundled JRE.

**Comment by holmbech** [comment]
Yup. Looking at it now...

**Comment by holmbech** [comment]
BTW java 9 is end of life: http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html

**Comment by holmbech** [comment]
version 1.38 now with bundled jre

**Comment by arkadiuszczapiewskinordea** [comment]
Really great!!!!! :) Thanks!!!!!
